/**
 * lib/agent-executor.ts — Runs agent tasks in isolated tmux sessions.
 * Generates per-agent shell scripts and manages execution lifecycle.
 */
import { Agent, ToolChoice } from '@/store/types';
import { toolChoiceToLabel } from './agent-tool-router';
import { getHomePath } from '@/lib/home-path';

const MAX_CONCURRENT = 2;

const DEFAULT_TIMEOUT_SEC = 600; // 10 minutes

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function paths() {
  const home = getHomePath();
  const shellyDir = `${home}/.shelly`;
  const agentsDir = `${shellyDir}/agents`;
  const tmpDir = `${shellyDir}/tmp`;
  const locksDir = `${agentsDir}/locks`;
  const logsDir = `${agentsDir}/logs`;
  return {
    home,
    shellyDir,
    agentsDir,
    tmpDir,
    locksDir,
    logsDir,
    envFile: `${agentsDir}/.env`,
  };
}

/**
 * Generate a per-agent script: run-agent-{id}.sh
 * All values pre-computed in TypeScript, embedded as bash string literals.
 */
export function generateRunScript(agent: Agent): string {
  const { home, tmpDir, locksDir, logsDir, envFile } = paths();
  const agentId = agent.id;
  const resultFile = `${tmpDir}/agent-result-${agentId}.md`;
  const lockFile = `${locksDir}/${agentId}.pid`;
  const logDir = `${logsDir}/${agentId}`;
  const toolLabel = toolChoiceToLabel(agent.tool);

  const slug = agent.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const outputDir = agent.outputPath.replace(/^~/, home).replace(/^\$HOME/, home);

  const escapedPrompt = agent.prompt.replace(/'/g, "'\\''");

  const toolCommand = generateToolCommand(agent.tool, escapedPrompt, agent.prompt);

  return `#!/bin/bash
# run-agent-${agentId}.sh — Auto-generated by Shelly for agent: ${agent.name}
# Do not edit manually.
set -euo pipefail

AGENT_ID=${shellQuote(agentId)}
RESULT_FILE=${shellQuote(resultFile)}
LOCK_FILE=${shellQuote(lockFile)}
LOG_DIR=${shellQuote(logDir)}
TIMEOUT=${DEFAULT_TIMEOUT_SEC}
OUTPUT_DIR=${shellQuote(outputDir)}
SLUG=${shellQuote(slug)}
TOOL_LABEL=${shellQuote(toolLabel)}
ENV_FILE=${shellQuote(envFile)}
LOCKS_DIR=${shellQuote(locksDir)}
TMP_DIR=${shellQuote(tmpDir)}
MAX_CONCURRENT=${MAX_CONCURRENT}
REGISTRY_LOCK=""
REGISTRY_LOCK_ACQUIRED=0
BACKEND_ERROR_FILE="$RESULT_FILE.backend-error"

START_TIME=$(date +%s)

export HOME="${home}"
export PATH="$HOME/.local/bin:$PATH"

cleanup() {
  if [ "\${REGISTRY_LOCK_ACQUIRED:-0}" = "1" ] && [ -n "\${REGISTRY_LOCK:-}" ] && [ -d "$REGISTRY_LOCK" ]; then
    rmdir "$REGISTRY_LOCK" 2>/dev/null || true
  fi
  rm -f "$LOCK_FILE"
}
json_escape_text() {
  text="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json,sys; print(json.dumps(sys.argv[1], ensure_ascii=False)[1:-1], end="")' "$text"
  else
    printf '%s' "$text" | tr '\\n\\r\\t' '   ' | sed 's/\\/\\\\/g; s/"/\\"/g'
  fi
}
write_failure_log() {
  code="$1"
  line="$2"
  END_TIME=$(date +%s)
  DURATION=$(( (END_TIME - START_TIME) * 1000 ))
  TS=$(date +%s)
  PREVIEW=$(printf 'Agent script failed before producing a result. exit=%s line=%s. PATH=%s' "$code" "$line" "$PATH" | head -c 500 | tr '\\n' ' ')
  PREVIEW_JSON=$(json_escape_text "$PREVIEW")
  TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
  cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"error","outputPreview":"$PREVIEW_JSON","durationMs":$DURATION,"toolUsed":"$TOOL_LABEL_JSON","errorMessage":"$PREVIEW_JSON"}
LOGEOF
}
finish() {
  code=$?
  if [ "$code" -ne 0 ]; then
    write_failure_log "$code" "\${BASH_LINENO[0]:-unknown}" || true
  fi
  cleanup
}

json_string_file() {
  file="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import json,sys; print(json.dumps(open(sys.argv[1], "r", encoding="utf-8", errors="replace").read(), ensure_ascii=False), end="")' "$file"
  else
    printf '"'
    sed 's/\r/ /g; s/\t/ /g; s/\\/\\\\/g; s/"/\\"/g; s/$/\\n/' "$file" | tr -d '\\n'
    printf '"'
  fi
}

extract_ai_content() {
  file="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$file" <<'PYEOF'
import json
import sys

path = sys.argv[1]
text = open(path, "r", encoding="utf-8", errors="replace").read()
try:
    data = json.loads(text)
except Exception:
    sys.stdout.write(text)
    raise SystemExit(0)

content = None
try:
    content = data.get("choices", [{}])[0].get("message", {}).get("content")
except Exception:
    content = None
if not content:
    try:
        content = data.get("choices", [{}])[0].get("text")
    except Exception:
        content = None
if not content:
    try:
        parts = data.get("candidates", [{}])[0].get("content", {}).get("parts", [])
        content = "\\n".join(part.get("text", "") for part in parts if part.get("text"))
    except Exception:
        content = None

err = data.get("error") or data.get("message")
if content:
    sys.stdout.write(content)
elif err:
    sys.stdout.write("API error: " + (err if isinstance(err, str) else json.dumps(err, ensure_ascii=False)))
    raise SystemExit(2)
else:
    sys.stdout.write(text)
PYEOF
  else
    if grep -q '"error"' "$file" 2>/dev/null; then
      printf 'API error response: '
      head -c 4000 "$file"
      return 2
    fi
    cat "$file"
  fi
}
local_context_fallback() {
  local reason="$1"
  echo "# Local Context Fallback"
  echo
  echo "Local LLM was unavailable, so Shelly saved a local-context digest instead of failing silently."
  echo
  echo "- reason: $reason"
  echo "- expected endpoint: \${LOCAL_URL%/}/v1/chat/completions"
  echo "- expected model: \${LOCAL_MODEL:-unknown}"
  echo
  echo "## Candidate Hooks"
  if [ -s "\${LOCAL_CONTEXT_FILE:-}" ]; then
    grep -E '^(###|####|- |[0-9a-f]{7,12} )' "$LOCAL_CONTEXT_FILE" 2>/dev/null | head -n 80 || true
  else
    echo "- No local context file was generated."
  fi
  echo
  echo "## Next Fix"
  echo "Start a local OpenAI-compatible Qwen3-8B server or set LOCAL_LLM_URL in ~/.shelly/agents/.env."
}

# Create directories before installing the failure trap so JSON logs have a target.
mkdir -p '${tmpDir}' '${locksDir}' "$LOG_DIR"
trap finish EXIT

# Source environment
[ -f "$ENV_FILE" ] && source "$ENV_FILE"

PROJECT_DIR="\${SHELLY_CONTENT_PROJECT:-$HOME/projects/shelly-content-studio}"
SOURCE_REGISTRY_FILE="\${SOURCE_REGISTRY_FILE:-$PROJECT_DIR/sources/source-registry.tsv}"
mkdir -p "$(dirname "$SOURCE_REGISTRY_FILE")"
touch "$SOURCE_REGISTRY_FILE"
SOURCE_CONTEXT=""
if [ -s "$SOURCE_REGISTRY_FILE" ]; then
  SOURCE_CONTEXT=$(printf '\\n\\nKnown source URLs already used. Avoid duplicates unless essential:\\n'; tail -n 120 "$SOURCE_REGISTRY_FILE" | awk -F '\\t' '{ if ($4 != "") print "- " $4 " (" $1 ", " $2 ")" }')
fi
LOCAL_CONTEXT_FILE="$TMP_DIR/local-context-$AGENT_ID.txt"
{
  echo
  echo "## Local project context"
  if [ -f "$PROJECT_DIR/AI_CONTEXT.md" ]; then
    echo
    echo "### AI_CONTEXT.md"
    head -c 8000 "$PROJECT_DIR/AI_CONTEXT.md" || true
    echo
  fi
  for dir in "$PROJECT_DIR/drafts/x" "$PROJECT_DIR/sources/x" "$PROJECT_DIR/drafts/articles" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/30_Build_Log" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/90_Log/Agent_Output"; do
    [ -d "$dir" ] || continue
    echo
    echo "### Recent files: $dir"
    find "$dir" -type f -name '*.md' 2>/dev/null | sort | tail -n 6 | while read -r file; do
      echo
      echo "#### $file"
      head -c 3000 "$file" || true
      echo
    done
  done
  for repo in "$HOME/hw" "$HOME/projects/shelly-content-studio"; do
    [ -d "$repo/.git" ] || continue
    echo
    echo "### Recent git log: $repo"
    git -C "$repo" log --oneline -8 2>/dev/null || true
    echo
    echo "### Current git status: $repo"
    git -C "$repo" status --short 2>/dev/null || true
  done
} > "$LOCAL_CONTEXT_FILE"
if [ -s "$LOCAL_CONTEXT_FILE" ]; then
  SOURCE_CONTEXT="$SOURCE_CONTEXT\\n\\n$(head -c 20000 "$LOCAL_CONTEXT_FILE")"
fi

# Global concurrency check
ACTIVE_COUNT=$(find "$LOCKS_DIR" -name '*.pid' -exec sh -c 'kill -0 $(cat "{}") 2>/dev/null && echo 1' \\; | wc -l)
if [ "$ACTIVE_COUNT" -ge "$MAX_CONCURRENT" ]; then
  TS=$(date +%s)
  TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
  cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"skipped","outputPreview":"global concurrency limit reached","durationMs":0,"toolUsed":"$TOOL_LABEL_JSON"}
LOGEOF
  exit 0
fi

# Per-agent concurrency lock
if [ -f "$LOCK_FILE" ]; then
  OLD_PID=$(cat "$LOCK_FILE")
  if kill -0 "$OLD_PID" 2>/dev/null; then
    TS=$(date +%s)
    TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
    cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"skipped","outputPreview":"previous run still active","durationMs":0,"toolUsed":"$TOOL_LABEL_JSON"}
LOGEOF
    exit 0
  fi
  rm -f "$LOCK_FILE"
fi

# Acquire lock
echo $$ > "$LOCK_FILE"

# Execute tool
rm -f "$BACKEND_ERROR_FILE"
${toolCommand}

# Check result
END_TIME=$(date +%s)
DURATION=$(( (END_TIME - START_TIME) * 1000 ))

if [ -f "$RESULT_FILE" ] && [ -s "$RESULT_FILE" ] && [ ! -f "$BACKEND_ERROR_FILE" ]; then
  PREVIEW=$(head -c 500 "$RESULT_FILE" | tr '\\n' ' ')
  STATUS="success"
  ERROR_MESSAGE=""

  # Copy to output directory
  mkdir -p "$OUTPUT_DIR"
  DATE=$(date +%Y-%m-%d)
  SAVED_FILE="$OUTPUT_DIR/$DATE-$SLUG.md"
  cp "$RESULT_FILE" "$SAVED_FILE"

  if [ -n "\${OBSIDIAN_VAULT_PATH:-}" ] && [ -d "$OBSIDIAN_VAULT_PATH" ]; then
    OBSIDIAN_TARGET="90_Log/Agent_Output"
    case "$OUTPUT_DIR" in
      *drafts/substack*) OBSIDIAN_TARGET="50_Drafts/Substack" ;;
      *drafts/x*) OBSIDIAN_TARGET="50_Drafts/X" ;;
      *drafts/articles*) OBSIDIAN_TARGET="50_Drafts/Substack" ;;
      *sources*) OBSIDIAN_TARGET="20_Literature/Papers" ;;
      *images/prompts*) OBSIDIAN_TARGET="60_Experiments/Image_Prompts" ;;
      *evals*) OBSIDIAN_TARGET="90_Log/Agent_Evals" ;;
    esac
    mkdir -p "$OBSIDIAN_VAULT_PATH/$OBSIDIAN_TARGET"
    cp "$SAVED_FILE" "$OBSIDIAN_VAULT_PATH/$OBSIDIAN_TARGET/$DATE-$SLUG.md"
  fi

  REGISTRY_LOCK="$SOURCE_REGISTRY_FILE.lock"
  REGISTRY_LOCK_ACQUIRED=0
  lock_attempt=0
  until mkdir "$REGISTRY_LOCK" 2>/dev/null; do
    lock_attempt=$((lock_attempt + 1))
    if [ "$lock_attempt" -ge 30 ]; then
      break
    fi
    sleep 1
  done
  if [ "$lock_attempt" -lt 30 ]; then
    REGISTRY_LOCK_ACQUIRED=1
  fi
  { grep -Eo 'https?://[^][ )<>"'"'"']+' "$RESULT_FILE" 2>/dev/null || true; } | sed 's/[.,;)]$//' | sort -u | while read -r url; do
    [ -n "$url" ] || continue
    if ! awk -F '\\t' -v url="$url" '$4 == url { found=1 } END { exit found ? 0 : 1 }' "$SOURCE_REGISTRY_FILE"; then
      printf '%s\\t%s\\t%s\\t%s\\n' "$(date -Iseconds)" "$AGENT_ID" "$TOOL_LABEL" "$url" >> "$SOURCE_REGISTRY_FILE"
    fi
  done
  if [ "$REGISTRY_LOCK_ACQUIRED" = "1" ] && [ -d "$REGISTRY_LOCK" ]; then
    rmdir "$REGISTRY_LOCK" 2>/dev/null || true
    REGISTRY_LOCK_ACQUIRED=0
    REGISTRY_LOCK=""
  fi
else
  if [ -f "$RESULT_FILE" ] && [ -s "$RESULT_FILE" ]; then
    PREVIEW=$(head -c 500 "$RESULT_FILE" | tr '\\n' ' ')
  else
    PREVIEW="Agent produced no output. Check backend configuration and required commands. Tool=$TOOL_LABEL PATH=$PATH"
  fi
  ERROR_MESSAGE="$PREVIEW"
  STATUS="error"
fi

# Log run result
TS=$(date +%s)
PREVIEW_JSON=$(json_escape_text "$PREVIEW")
TOOL_LABEL_JSON=$(json_escape_text "$TOOL_LABEL")
ERROR_MESSAGE_JSON=$(json_escape_text "$ERROR_MESSAGE")
cat > "$LOG_DIR/$TS.json" << LOGEOF
{"agentId":"$AGENT_ID","timestamp":\${TS}000,"status":"$STATUS","outputPreview":"$PREVIEW_JSON","durationMs":$DURATION,"toolUsed":"$TOOL_LABEL_JSON","errorMessage":"$ERROR_MESSAGE_JSON"}
LOGEOF

# Prune old logs (keep last 30)
ls -t "$LOG_DIR"/*.json 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null || true

# Cleanup temp
rm -f "$RESULT_FILE" "$BACKEND_ERROR_FILE"
`;
}

function generateToolCommand(tool: ToolChoice, escapedPrompt: string, rawPrompt: string): string {
  const resultVar = '"$RESULT_FILE"';
  switch (tool.type) {
    case 'cli':
      if (tool.cli === 'claude') {
        return `echo 'Claude Code is available in Terminal only. Background Claude execution is disabled.' > ${resultVar}`;
      }
      if (tool.cli === 'codex') {
        return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
if command -v codex >/dev/null 2>&1; then
  timeout "$TIMEOUT" codex exec "$(cat "$PROMPT_FILE")" > ${resultVar} 2>&1 || true
else
  echo 'Codex CLI is not installed or not on PATH. Run shelly-runtime-update codex, then codex-login.' > ${resultVar}
fi
rm -f "$PROMPT_FILE"`;
      }
      return `echo 'Gemini CLI is experimental in Shelly. Use Gemini API for background agents.' > ${resultVar}`;
    case 'gemini-api':
      return geminiApiCommand(escapedPrompt, resultVar, tool.model);
    case 'local':
      const localModel = (tool.model || 'Qwen3-8B').replace(/"/g, '\\"');
      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
	printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
	PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
	LOCAL_URL="\${LOCAL_LLM_URL:-http://127.0.0.1:8080}"
	LOCAL_MODEL="\${LOCAL_LLM_MODEL:-${localModel}}"
	set +e
	timeout "$TIMEOUT" curl -s "\${LOCAL_URL%/}/v1/chat/completions" \\
	  -H "Content-Type: application/json" \\
	  -d "{\\"model\\":\\"$LOCAL_MODEL\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":$PROMPT_JSON}],\\"max_tokens\\":4096}" \\
	  > "$RESULT_FILE.response.json" 2> "$RESULT_FILE.stderr"
	LOCAL_EXIT=$?
	set -e
	if [ "$LOCAL_EXIT" -ne 0 ] || [ ! -s "$RESULT_FILE.response.json" ]; then
	  local_context_fallback "curl exit=$LOCAL_EXIT $(head -c 240 "$RESULT_FILE.stderr" 2>/dev/null | tr '\\n' ' ')" > ${resultVar}
	else
	  extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
	fi
	rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
	rm -f "$PROMPT_FILE"`;
    case 'perplexity':
      const perplexityModel = tool.model || 'sonar';
	      return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
	printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
	PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
	MODEL='${perplexityModel.replace(/'/g, "'\\''")}'
	if [ -z "\${PERPLEXITY_API_KEY:-}" ]; then
	  echo 'Perplexity API key is not set. Add PERPLEXITY_API_KEY to ~/.shelly/agents/.env.' > ${resultVar}
	  touch "$BACKEND_ERROR_FILE"
	else
	timeout "$TIMEOUT" curl -s https://api.perplexity.ai/chat/completions \\
	  -H "Authorization: Bearer $PERPLEXITY_API_KEY" \\
	  -H "Content-Type: application/json" \\
	  -d "{\\"model\\":\\"$MODEL\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":$PROMPT_JSON}]}" \\
	  > "$RESULT_FILE.response.json" 2> "$RESULT_FILE.stderr" || true
	extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
	rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
	fi
	rm -f "$PROMPT_FILE"`;
    case 'ab-article-eval':
      return articleEvalCommand(rawPrompt, resultVar, tool.localModel, tool.codexCmd);
    case 'auto':
      return `if [ -n "\${GEMINI_API_KEY:-}" ]; then
  ${geminiApiCommand(escapedPrompt, resultVar)}
elif command -v codex >/dev/null 2>&1; then
  PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
  printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
  timeout "$TIMEOUT" codex exec "$(cat "$PROMPT_FILE")" > ${resultVar} 2>&1 || true
  rm -f "$PROMPT_FILE"
else
  echo 'No background agent backend is configured. Add a Gemini API key or use Codex in Terminal.' > ${resultVar}
fi`;
  }
}

function articleEvalCommand(rawPrompt: string, resultVar: string, localModel?: string, codexCmd?: string): string {
  const promptMarker = `SHELLY_AB_PROMPT_${Math.random().toString(36).slice(2)}`;
  const localModelValue = (localModel || 'Qwen3-8B').replace(/"/g, '\\"');
  const codexCmdValue = (codexCmd || 'codex').replace(/"/g, '\\"');
  return `PROJECT_DIR="\${SHELLY_CONTENT_PROJECT:-$HOME/projects/shelly-content-studio}"
LOCAL_URL="\${LOCAL_LLM_URL:-http://127.0.0.1:8080}"
LOCAL_MODEL="\${LOCAL_LLM_MODEL:-${localModelValue}}"
CODEX_CMD="\${CODEX_CMD:-${codexCmdValue}}"
RUN_TS=$(date +%Y%m%d-%H%M%S)
RUN_DIR="$PROJECT_DIR/evals/$RUN_TS-$SLUG"
mkdir -p "$RUN_DIR"

cat > "$RUN_DIR/user-request.md" <<'${promptMarker}'
${rawPrompt}
${promptMarker}

{
  echo '# Project Context'
  if [ -f "$PROJECT_DIR/AI_CONTEXT.md" ]; then cat "$PROJECT_DIR/AI_CONTEXT.md"; fi
  echo
  echo '# Recent Sources'
  for dir in "$PROJECT_DIR/sources" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/20_Literature/Papers" "\${OBSIDIAN_VAULT_PATH:-/sdcard/Documents/ObsidianVault}/30_Build_Log"; do
    [ -d "$dir" ] || continue
    find "$dir" -type f -name '*.md' 2>/dev/null | sort | tail -n 8 | while read -r file; do
      echo
      echo "## Source: $file"
      head -c 6000 "$file" || true
      echo
    done
  done
} > "$RUN_DIR/context.md"

cat > "$RUN_DIR/prompt.md" <<'PROMPTEOF'
あなたは日本語のSubstack記事の編集者です。

目的:
STEAM x AIを、AI導入論ではなく「AIを理解したうえで基礎学力を再定義する議論」として記事化してください。

必須観点:
- 語彙力
- 読解力
- 想像力 / 創造力
- 判断力 / 批判的思考
- 公教育で長く重視されてきた基礎学力との接続

制約:
- 事実と解釈を分ける
- 引用元やURLが文脈に含まれる場合は活用する
- 過剰な断定やAI万能論を避ける
- 日本語で、公開前の下書きとして使える密度にする

PROMPTEOF
{
  echo
  echo '# User Request'
  cat "$RUN_DIR/user-request.md"
  echo
  cat "$RUN_DIR/context.md"
} >> "$RUN_DIR/prompt.md"

PROMPT_JSON=$(json_string_file "$RUN_DIR/prompt.md")

LOCAL_START=$(date +%s)
set +e
timeout "$TIMEOUT" curl -s "\${LOCAL_URL%/}/v1/chat/completions" \\
  -H "Content-Type: application/json" \\
  -d "{\\"model\\":\\"$LOCAL_MODEL\\",\\"messages\\":[{\\"role\\":\\"user\\",\\"content\\":$PROMPT_JSON}],\\"temperature\\":0.7,\\"max_tokens\\":4096}" \\
  > "$RUN_DIR/local.response.json" 2> "$RUN_DIR/local.stderr.log"
LOCAL_EXIT=$?
set -e
LOCAL_END=$(date +%s)
if [ "$LOCAL_EXIT" -eq 0 ]; then
  extract_ai_content "$RUN_DIR/local.response.json" > "$RUN_DIR/local-qwen3-8b.md" 2>> "$RUN_DIR/local.stderr.log" || true
else
  echo "Local LLM failed with exit $LOCAL_EXIT" > "$RUN_DIR/local-qwen3-8b.md"
fi

CODEX_START=$(date +%s)
set +e
if command -v "$CODEX_CMD" >/dev/null 2>&1; then
  timeout "$TIMEOUT" "$CODEX_CMD" exec "$(cat "$RUN_DIR/prompt.md")" > "$RUN_DIR/codex.md" 2> "$RUN_DIR/codex.stderr.log"
  CODEX_EXIT=$?
else
  echo "Codex CLI not found: $CODEX_CMD" > "$RUN_DIR/codex.md"
  echo "Codex CLI not found: $CODEX_CMD" > "$RUN_DIR/codex.stderr.log"
  CODEX_EXIT=127
fi
set -e
CODEX_END=$(date +%s)

local_bytes=$(wc -c < "$RUN_DIR/local-qwen3-8b.md" | tr -d ' ')
codex_bytes=$(wc -c < "$RUN_DIR/codex.md" | tr -d ' ')
local_headings=$(grep -c '^#' "$RUN_DIR/local-qwen3-8b.md" 2>/dev/null || true)
codex_headings=$(grep -c '^#' "$RUN_DIR/codex.md" 2>/dev/null || true)
local_links=$(grep -Eo 'https?://[^ )]+' "$RUN_DIR/local-qwen3-8b.md" 2>/dev/null | wc -l | tr -d ' ')
codex_links=$(grep -Eo 'https?://[^ )]+' "$RUN_DIR/codex.md" 2>/dev/null | wc -l | tr -d ' ')

cat > "$RUN_DIR/metrics.json" <<METRICSEOF
{"agentId":"$AGENT_ID","timestamp":"$RUN_TS","localModel":"$LOCAL_MODEL","codexCmd":"$CODEX_CMD","localExit":$LOCAL_EXIT,"codexExit":$CODEX_EXIT,"localDurationSec":$((LOCAL_END - LOCAL_START)),"codexDurationSec":$((CODEX_END - CODEX_START)),"localBytes":$local_bytes,"codexBytes":$codex_bytes,"localHeadings":$local_headings,"codexHeadings":$codex_headings,"localLinks":$local_links,"codexLinks":$codex_links}
METRICSEOF

cat > "$RUN_DIR/eval.md" <<EVALEOF
# A/B Evaluation

## Metrics
\`\`\`json
$(cat "$RUN_DIR/metrics.json")
\`\`\`

## Quick Read
- Qwen/local output: $RUN_DIR/local-qwen3-8b.md
- Codex output: $RUN_DIR/codex.md
- Prompt: $RUN_DIR/prompt.md
- Context: $RUN_DIR/context.md

## Manual Rubric
- Thesis alignment: AI-era STEAM = foundational academic ability
- Source faithfulness
- Japanese readability
- Article structure
- Originality
- Publishability
EVALEOF

cat > ${resultVar} <<RESULTEOF
# Qwen3-8B vs Codex A/B Article Eval

Run directory: $RUN_DIR

## Verdict Stub
Review \`eval.md\`, \`local-qwen3-8b.md\`, and \`codex.md\`.

## Metrics
\`\`\`json
$(cat "$RUN_DIR/metrics.json")
\`\`\`

## Local Qwen Preview
$(head -n 40 "$RUN_DIR/local-qwen3-8b.md")

## Codex Preview
$(head -n 40 "$RUN_DIR/codex.md")
RESULTEOF`;
}

function geminiApiCommand(escapedPrompt: string, resultVar: string, model?: string): string {
  const defaultModel = model || 'gemini-2.0-flash';
  return `PROMPT_FILE="$HOME/.shelly/tmp/agent-prompt-$AGENT_ID.txt"
printf '%s\\n%s\\n' '${escapedPrompt}' "$SOURCE_CONTEXT" > "$PROMPT_FILE"
PROMPT_JSON=$(json_string_file "$PROMPT_FILE")
MODEL="\${GEMINI_MODEL:-${defaultModel.replace(/"/g, '\\"')}}"
if [ -z "\${GEMINI_API_KEY:-}" ]; then
  echo 'Gemini API key is not set. Add it in Settings before running background agents.' > ${resultVar}
  touch "$BACKEND_ERROR_FILE"
else
  timeout "$TIMEOUT" curl -s "https://generativelanguage.googleapis.com/v1beta/models/$MODEL:generateContent" \\
    -H "Content-Type: application/json" \\
    -H "x-goog-api-key: $GEMINI_API_KEY" \\
    -d "{\\"contents\\":[{\\"role\\":\\"user\\",\\"parts\\":[{\\"text\\":$PROMPT_JSON}]}],\\"generationConfig\\":{\\"maxOutputTokens\\":4096,\\"temperature\\":0.7}}" \\
    > "$RESULT_FILE.response.json" 2> "$RESULT_FILE.stderr" || true
  extract_ai_content "$RESULT_FILE.response.json" > ${resultVar} 2>> "$RESULT_FILE.stderr" || { touch "$BACKEND_ERROR_FILE"; [ -s ${resultVar} ] || cat "$RESULT_FILE.stderr" > ${resultVar}; }
  rm -f "$RESULT_FILE.response.json" "$RESULT_FILE.stderr"
fi
rm -f "$PROMPT_FILE"`;
}

export function getScriptPath(agentId: string): string {
  return `${paths().agentsDir}/run-agent-${agentId}.sh`;
}

export function generateInstallCommands(agent: Agent): string[] {
  const { agentsDir, tmpDir, locksDir, logsDir } = paths();
  const scriptPath = getScriptPath(agent.id);
  return [
    `mkdir -p '${agentsDir}' '${tmpDir}' '${locksDir}' '${logsDir}/${agent.id}'`,
    `chmod +x '${scriptPath}'`,
  ];
}

export function generateStopCommand(agentId: string): string {
  const pidFile = `${paths().locksDir}/${agentId}.pid`;
  return `pid_file=${shellQuote(pidFile)}; if [ -f "$pid_file" ]; then pid="$(cat "$pid_file")"; kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true; sleep 1; kill -KILL -- "-$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null || true; rm -f "$pid_file"; fi`;
}
